import { AnalysisResult, ToolId } from "./types";

function rand(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export async function getMockResponse(
  toolId: ToolId,
  input: string
): Promise<{ text: string; analysis: AnalysisResult }> {
  await new Promise((r) => setTimeout(r, 1200 + Math.random() * 800));

  switch (toolId) {
    case "general":
      return generalResponse(input);
    case "image-detection":
      return imageResponse(input);
    case "text-detection":
      return textResponse(input);
    case "video-detection":
      return videoResponse(input);
    case "fact-check":
      return factCheckResponse(input);
    case "bot-detection":
      return botResponse(input);
  }
}

function generalResponse(input: string): { text: string; analysis: AnalysisResult } {
  const outcomes = ["ai-generated", "authentic", "likely-false", "likely-true", "unverified"] as const;
  const verdict = outcomes[Math.floor(Math.random() * outcomes.length)];
  const confidence = rand(63, 96);
  const riskMap = {
    "ai-generated": "high", authentic: "low", "likely-false": "high", "likely-true": "low", unverified: "medium",
  } as const;

  const summaries: Record<typeof verdict, string> = {
    "ai-generated": "Content shows strong indicators of being synthetically generated or manipulated.",
    authentic: "No significant indicators of manipulation or synthetic generation were found.",
    "likely-false": "The content contains claims that contradict multiple credible sources.",
    "likely-true": "The content is consistent with information from verified sources.",
    unverified: "Insufficient data to reach a definitive conclusion. Further review is recommended.",
  };

  const verdictLabels: Record<typeof verdict, string> = {
    "ai-generated": "AI-Generated / Manipulated",
    authentic: "Appears Authentic",
    "likely-false": "Likely Misinformation",
    "likely-true": "Likely Credible",
    unverified: "Unverified",
  };

  return {
    text: `Analysis complete. Verdict: **${verdictLabels[verdict]}** (${confidence}% confidence). ${summaries[verdict]}`,
    analysis: {
      verdict,
      confidence,
      riskLevel: riskMap[verdict],
      summary: summaries[verdict],
      details: [
        { label: "Content type detected", value: ["Text / article", "Image", "Video clip", "Social media post", "URL"][rand(0, 4)], flag: "info" },
        { label: "Synthetic media indicators", value: verdict === "ai-generated" ? "Present" : "None detected", flag: verdict === "ai-generated" ? "warn" : "ok" },
        { label: "Claim verification", value: verdict === "likely-false" ? "Contradicted by sources" : verdict === "likely-true" ? "Corroborated" : "Inconclusive", flag: verdict === "likely-false" ? "warn" : verdict === "likely-true" ? "ok" : "info" },
        { label: "Source credibility", value: ["High", "Medium", "Low", "Unknown"][rand(0, 3)], flag: "info" },
        { label: "Flagged by fact-checkers", value: verdict === "likely-false" ? `${rand(1, 4)} records found` : "None", flag: verdict === "likely-false" ? "warn" : "ok" },
      ],
    },
  };
}

function imageResponse(input: string): { text: string; analysis: AnalysisResult } {
  const isAI = Math.random() > 0.4;
  const confidence = rand(72, 97);
  return {
    text: isAI
      ? `Analysis complete. The image shows **${confidence}% probability** of being AI-generated. Several telltale artifacts were detected typical of diffusion-model outputs.`
      : `Analysis complete. The image appears **authentic** with ${confidence}% confidence. No significant AI generation artifacts were found.`,
    analysis: {
      verdict: isAI ? "ai-generated" : "authentic",
      confidence,
      riskLevel: isAI ? "high" : "low",
      summary: isAI
        ? "High likelihood this image was generated by an AI model (e.g. Stable Diffusion, Midjourney, DALL·E)."
        : "Image metadata and pixel-level analysis suggest this is an unaltered photograph.",
      details: isAI
        ? [
            { label: "GAN / Diffusion artifacts", value: "Detected", flag: "warn" },
            { label: "EXIF metadata", value: "Missing or inconsistent", flag: "warn" },
            { label: "Noise pattern", value: "Synthetic — does not match camera sensor noise", flag: "warn" },
            { label: "Facial geometry (if present)", value: "Slight asymmetry in ear/hair regions", flag: "warn" },
            { label: "Compression fingerprint", value: "No JPEG double-compression detected", flag: "info" },
          ]
        : [
            { label: "GAN / Diffusion artifacts", value: "None detected", flag: "ok" },
            { label: "EXIF metadata", value: "Present and consistent", flag: "ok" },
            { label: "Noise pattern", value: "Consistent with camera sensor", flag: "ok" },
            { label: "Compression fingerprint", value: "Normal JPEG compression history", flag: "ok" },
          ],
    },
  };
}

function textResponse(input: string): { text: string; analysis: AnalysisResult } {
  const isAI = Math.random() > 0.45;
  const confidence = rand(68, 95);
  return {
    text: isAI
      ? `The submitted text has a **${confidence}% probability** of being AI-generated. Linguistic patterns characteristic of large language models were identified.`
      : `The text appears to be **human-written** with ${confidence}% confidence. Writing style, burstiness, and perplexity scores are consistent with authentic authorship.`,
    analysis: {
      verdict: isAI ? "ai-generated" : "authentic",
      confidence,
      riskLevel: isAI ? "high" : "low",
      summary: isAI
        ? "Text exhibits low perplexity and low burstiness — typical signatures of LLM-generated content."
        : "Text perplexity and burstiness fall within expected human-writing ranges.",
      details: isAI
        ? [
            { label: "Perplexity score", value: "Low (12.4) — typical of LLM output", flag: "warn" },
            { label: "Burstiness", value: "0.18 — unusually uniform sentence length", flag: "warn" },
            { label: "Repetitive phrasing", value: "3 instances detected", flag: "warn" },
            { label: "Hedging language", value: "High frequency ('it is worth noting…')", flag: "warn" },
            { label: "Named entity consistency", value: "All entities verifiable", flag: "ok" },
          ]
        : [
            { label: "Perplexity score", value: "Normal (48.2)", flag: "ok" },
            { label: "Burstiness", value: "0.72 — natural variation in sentence length", flag: "ok" },
            { label: "Stylistic fingerprint", value: "Consistent human authorship patterns", flag: "ok" },
          ],
    },
  };
}

function videoResponse(input: string): { text: string; analysis: AnalysisResult } {
  const isDeepfake = Math.random() > 0.5;
  const confidence = rand(70, 96);
  return {
    text: isDeepfake
      ? `Deepfake analysis complete. **${confidence}% confidence** of synthetic manipulation detected. Face-swap or lip-sync artifacts were found across multiple frames.`
      : `Video appears **authentic** with ${confidence}% confidence. Frame-by-frame analysis found no deepfake artifacts.`,
    analysis: {
      verdict: isDeepfake ? "manipulated" : "authentic",
      confidence,
      riskLevel: isDeepfake ? "high" : "low",
      summary: isDeepfake
        ? "Face-region inconsistencies detected across frames, indicative of a deepfake or face-swap technique."
        : "Temporal consistency and facial landmark tracking show no signs of synthetic manipulation.",
      details: isDeepfake
        ? [
            { label: "Face-swap artifacts", value: "Detected in 34% of frames", flag: "warn" },
            { label: "Lip-sync consistency", value: "Desynchronisation detected (avg 120 ms)", flag: "warn" },
            { label: "Eye-blink frequency", value: "Abnormal (1.2× normal rate)", flag: "warn" },
            { label: "Lighting coherence", value: "Minor inconsistencies in shadow direction", flag: "warn" },
            { label: "Audio-visual alignment", value: "Drift detected in 2 segments", flag: "warn" },
          ]
        : [
            { label: "Face-swap artifacts", value: "None detected", flag: "ok" },
            { label: "Lip-sync consistency", value: "Aligned within 30 ms", flag: "ok" },
            { label: "Eye-blink frequency", value: "Normal", flag: "ok" },
            { label: "Lighting coherence", value: "Consistent throughout", flag: "ok" },
          ],
    },
  };
}

function factCheckResponse(input: string): { text: string; analysis: AnalysisResult } {
  const outcomes = ["likely-false", "likely-true", "unverified"] as const;
  const verdict = outcomes[Math.floor(Math.random() * outcomes.length)];
  const confidence = rand(60, 94);
  const verdictLabels = { "likely-false": "Likely False", "likely-true": "Likely True", unverified: "Unverified" };
  const riskMap = { "likely-false": "high", "likely-true": "low", unverified: "medium" } as const;

  return {
    text:
      verdict === "likely-false"
        ? `Fact-check complete. This claim is rated **"${verdictLabels[verdict]}"** (${confidence}% confidence). Cross-referencing with ${rand(3, 8)} trusted sources found contradicting evidence.`
        : verdict === "likely-true"
        ? `Fact-check complete. This claim is rated **"${verdictLabels[verdict]}"** (${confidence}% confidence). Multiple reliable sources corroborate this statement.`
        : `Fact-check complete. This claim is **"${verdictLabels[verdict]}"** — insufficient evidence found to confirm or deny it.`,
    analysis: {
      verdict,
      confidence,
      riskLevel: riskMap[verdict],
      summary:
        verdict === "likely-false"
          ? "Multiple credible sources contradict this claim. It may be misleading or fabricated."
          : verdict === "likely-true"
          ? "The claim is consistent with reporting from several high-reliability sources."
          : "Available sources do not provide enough information to conclusively verify this claim.",
      details: [
        {
          label: "Sources checked",
          value: `${rand(4, 12)} databases and news archives`,
          flag: "info",
        },
        {
          label: "Matching fact-check records",
          value: verdict === "unverified" ? "0 direct matches" : `${rand(2, 6)} matches found`,
          flag: verdict === "unverified" ? "warn" : verdict === "likely-false" ? "warn" : "ok",
        },
        {
          label: "Claim category",
          value: ["Health", "Politics", "Science", "Economy", "Technology"][rand(0, 4)],
          flag: "info",
        },
        {
          label: "First seen online",
          value: `${rand(1, 18)} months ago`,
          flag: "info",
        },
      ],
      sources:
        verdict !== "unverified"
          ? [
              { title: "Reuters Fact Check", url: "#", reliability: "high" },
              { title: "AP Fact Check", url: "#", reliability: "high" },
              { title: "Snopes", url: "#", reliability: "medium" },
            ]
          : [],
    },
  };
}

function botResponse(input: string): { text: string; analysis: AnalysisResult } {
  const isBot = Math.random() > 0.45;
  const confidence = rand(67, 96);
  return {
    text: isBot
      ? `Bot analysis complete. This account has a **${confidence}% bot probability**. Behavioural patterns strongly suggest automated or coordinated inauthentic behaviour.`
      : `Account analysis complete. This profile appears **human-operated** (${confidence}% confidence). No significant bot indicators were found.`,
    analysis: {
      verdict: isBot ? "bot" : "human",
      confidence,
      riskLevel: isBot ? "high" : "low",
      summary: isBot
        ? "Account exhibits multiple bot-like patterns: high-frequency posting, repetitive content, and suspicious follower/following ratios."
        : "Account activity patterns, posting frequency, and engagement ratios are consistent with genuine human behaviour.",
      details: isBot
        ? [
            { label: "Posting frequency", value: `${rand(40, 120)} posts/day — abnormally high`, flag: "warn" },
            { label: "Account age vs. activity", value: "High activity within first 24 h of creation", flag: "warn" },
            { label: "Follower/following ratio", value: "Irregular (follows many, few followers)", flag: "warn" },
            { label: "Content originality", value: `${rand(70, 95)}% retweets or copy-paste`, flag: "warn" },
            { label: "Profile completeness", value: "Missing bio or profile picture", flag: "warn" },
            { label: "Coordinated behaviour", value: "Matches ${rand(3,12)} known bot clusters", flag: "warn" },
          ]
        : [
            { label: "Posting frequency", value: `${rand(1, 8)} posts/day — normal`, flag: "ok" },
            { label: "Account age vs. activity", value: "Gradual growth over time", flag: "ok" },
            { label: "Follower/following ratio", value: "Balanced", flag: "ok" },
            { label: "Content originality", value: "Mostly original content", flag: "ok" },
            { label: "Profile completeness", value: "Complete profile with history", flag: "ok" },
          ],
    },
  };
}
