import { Tool } from "./types";

export const TOOLS: Tool[] = [
  {
    id: "general",
    label: "Misinformation Analysis",
    shortLabel: "Analysis",
    description: "Analyze any content — text, images, videos, or claims — for misinformation and AI-generated media",
    icon: "shield-alert",
    acceptsFile: true,
    fileTypes: "image/*,video/*",
    placeholder: "Paste a claim, article, URL, or upload a file to analyze...",
    color: "#818cf8",
  },
  {
    id: "image-detection",
    label: "AI Image Detection",
    shortLabel: "Images",
    description: "Detect AI-generated or manipulated images using metadata and visual analysis",
    icon: "image",
    acceptsFile: true,
    fileTypes: "image/*",
    placeholder: "Upload an image or paste a URL to analyze...",
    color: "#818cf8",
  },
  {
    id: "text-detection",
    label: "AI Text & News Detection",
    shortLabel: "Text / News",
    description: "Identify AI-written content and misinformation in news articles",
    icon: "file-text",
    placeholder: "Paste an article, headline, or any text to analyze...",
    color: "#34d399",
  },
  {
    id: "video-detection",
    label: "AI Video Detection",
    shortLabel: "Videos",
    description: "Analyze videos for deepfake manipulation and synthetic media",
    icon: "video",
    acceptsFile: true,
    fileTypes: "video/*",
    placeholder: "Upload a video or paste a URL to analyze...",
    color: "#f472b6",
  },
  {
    id: "fact-check",
    label: "Fact-Checking",
    shortLabel: "Fact-Check",
    description: "Verify claims against trusted databases and news sources",
    icon: "search-check",
    placeholder: "Enter a claim or statement to fact-check...",
    color: "#fbbf24",
  },
  {
    id: "bot-detection",
    label: "Bot Account Detection",
    shortLabel: "Bot Detector",
    description: "Analyze social media profiles for bot-like behaviour patterns",
    icon: "bot",
    placeholder: "Paste a profile URL or username to analyze...",
    color: "#fb923c",
  },
];
